- name: Install EPEL (required for redis on RHEL 9)
  ansible.builtin.dnf:
    name: epel-release
    state: present
  when: ansible_facts['distribution_major_version'] | int < 10

- name: Install redis/valkey package
  ansible.builtin.dnf:
    name: "{{ redis_package_name }}"
    state: present

- import_tasks: discover_conf_path_redhat.yml

- name: Allow redis/valkey through firewalld if remote access needed
  ansible.posix.firewalld:
    port: "{{ redis_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  when: redis_bind != "127.0.0.1"