---
nginx_package_name: nginx
nginx_service_name: nginx
nginx_conf_path: "/etc/nginx/sites-available/netbox.conf"
nginx_conf_enabled_path: "/etc/nginx/sites-enabled/netbox.conf"
nginx_uses_sites_enabled: true