# site.yml
---
- name: Deploy NetBox
  hosts: netbox_servers
  become: true
  vars_files:
    - vault/secrets.yml
  pre_tasks:
    - name: Fail on unsupported OS family
      ansible.builtin.assert:
        that:
          - ansible_facts['os_family'] in ['Debian', 'RedHat']
        fail_msg: "This playbook only supports Debian and RedHat OS families"
  roles:
    - postgresql
    - redis
    - netbox
    - nginx
