---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  tags: install

- name: restart netbox
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - netbox
    - netbox-rq
  tags: install

- name: restore netbox selinux context
  ansible.builtin.command: "restorecon -Rv {{ netbox_home }}"
  tags: install
